services:
  - type: web
    name: to-do_bend   # This should match the actual name of your web service on Render, not the URL
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
    startCommand: gunicorn config.wsgi:application
    autoDeploy: true
    preDeployCommand: python manage.py migrate
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: todo_db
          property: connectionString

databases:
  - name: todo_db
    plan: free
