services:
  - type: web
    name: to-do-bend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn todo_project.wsgi:application
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: todo_db
          property: connectionString
    preDeployCommand: python manage.py migrate && python manage.py collectstatic --noinput
