# Generated by Django 5.2.1 on 2025-05-14 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0004_todo_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='user',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='todo',
            name='user',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
